compile:
	g++ GridPosition.cpp -c -Wall
	g++ Board.cpp -c -Wall
	g++ MysteryMachine.cpp -c -Wall
	g++ driver.cpp Board.o GridPosition.o MysteryMachine.o -Wall -o driver.exe

run:
	./driver.exe

clean:
	del *.o
	del *.exe